### ISSUE TITLE
Original servo horn screws too short

### ISSUE THREAD

**Issue by nitrovent** [robomechanics/MiniRHex#1]
I am trying to assemble a leg-shaft-servo-part but running into issues connecting the shaft to the servo. 
(Step 10 of https://github.com/robomechanics/MiniRHex/tree/master/Assembly)

The original screws are just long enough to securely hold the horn itself. 
Maybe you could update the assembly instructions with an updated screw length (and required screw type)

**Comment by nikolaif399** [comment]
We've had the same issue. We ended up using a different screw than the 10mm m3 button head, we'll update the instructions when we have a better solution. Thank you for bringing this to our attention.

**Comment by jjoepayne** [comment]
Thanks for pointing out the issue, I'd recommend these bolts for the leg shafts:

https://www.mcmaster.com/92005a078

I will update the instructions and purchasing list to match this, thanks again!
