### ISSUE TITLE
Two different screws, nuts, and spacers

### ISSUE THREAD

**Issue by fdavulcu** [robomechanics/MiniRHex#2]
In [HardwareList](https://github.com/robomechanics/MiniRHex/tree/master/HardwareList), there are two files: MiniRhexHardware.xlsx and readme.md. In these files, the screws, nuts, and spacers are different:

| Part    | readme.md                               | MiniRhexHardware.xlsx                      |
|---------|-----------------------------------------|--------------------------------------------|
| Screws  | M3 x 0.5mm Thread, 10mm Long            | M2.5 x 0.45 mm Thread, 16 mm Long          |
| Nuts    | M3 x 0.5 mm Thread                      | M2.5 x 0.45 mm Thread                      |
| Spacers | 4.5 mm OD, 3 mm Long, for M3 Screw Size | 4.5 mm OD, 10 mm Long, for M2.5 Screw Size |

Which file is the correct one?

**Comment by nikolaif399** [comment]
Hey Furkan,
The readme.md file is correct, we're using m3 hardware. I removed the old file, thanks for bringing this to our attention!
