### ISSUE TITLE
When I compile code on Arduino, it shows me 'Dynamixel' does not name a type. What libraries should I import?

### ISSUE THREAD

**Issue by Beiyu-kk** [robomechanics/MiniRHex#4]
When I compile code on Arduino, it shows me 'Dynamixel' does not name a type. What libraries should I import? Thanks!
![image](https://user-images.githubusercontent.com/72841628/164987495-4e13e164-98c0-46f4-a237-dc94790a6f04.png)

**Comment by jjoepayne** [comment]
I believe your issue here is that you're using the Arduino IDE rather than the [Robotis OpenCM IDE](https://emanual.robotis.com/docs/en/software/opencm_ide/getting_started/).

Let me know if that doesn't fix your issues!

**Comment by beiyu-kk** [comment]
Thanks for your answer! I've succeed in getting the Rhex to move by Robotis OpenCM IDE. 

If I still want to control Rhex by Arduino what should I do?

**Comment by jjoepayne** [comment]
We have an [Arduino Compatible branch](https://github.com/robomechanics/MiniRHex/tree/arduino_compatible), although I'm not entirely sure we got it fully working. I think robotis has some content on getting it to work on [this wiki](https://emanual.robotis.com/docs/en/parts/controller/opencm904/#library-api).

**Comment by beiyu-kk** [comment]
Thanks a lot
